target: all
multitenancy_enabled: true

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

ingester:
  ring:
    replication_factor: 1

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/data/compactor

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/data/rules

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/data/alerts
